# Generated by Django 5.2.3 on 2025-07-01 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('festival', 'Festival'), ('networking', 'Networking'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='../media/images/events/%Y/%m/%d')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='event_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='events_even_start_t_33fd3e_idx'), models.Index(fields=['title'], name='events_even_title_aedf91_idx')],
            },
        ),
    ]
